### ISSUE TITLE
Is the text size changer really needed?

### ISSUE THREAD

**Issue by hajimehoshi** [ebiten-playground/ebiten-playground.github.io#17]
I think only 12 is enough. If we could remove this, the UI would be simpler.

**Comment by j7b** [comment]
It's basically there because it made life easier on my eyes and on some of the less-capable displays I use it on and browser zoom has unpleasant side effects. My intent after MDP was to add controls to the editor, probably in a dropdown, to set font face, size, and indent controls, upload, download, and format should probably be an editor control, let's track at https://github.com/ebiten-playground/ebiten-playground.github.io/issues/20
